//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сведения_о_заказе
    {
        public int ID { get; set; }
        public Nullable<int> ID_Заказа { get; set; }
        public Nullable<int> ID_Товара { get; set; }
        public string Коливество { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
